### ISSUE TITLE
[Question] How to run with Docker and environment variables?

### ISSUE THREAD

**Issue by SA7BNT** [J-Rios/TLG_JoinCaptchaBot#101]
Hello,

i´m trying to run the docker instance with other "environment variable" but it will not work for me. 

`docker run -d --name captcha-bot --env CAPTCHABOT_TOKEN="xxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxx" --env CAPTCHABOT_OWNER="xxxxxxxx" --env CAPTCHABOT_INIT_LANG="DE" --restart always captcha-bot`

The container is running, but not with language=DE. It always starts with language=EN

Whats my problem??

**Comment by J-Rios** [comment]
Hi,

Seems that initial language parse from enviroment variable was [missing in constants file](https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/21342c37561ce317083b685c9e04ec349b6d8593).

Fixed in master branch, please pull the changes and try again.

Regards.

**Comment by SA7BNT** [comment]
> Hi,
> 
> Seems that initial language parse from enviroment variable was [missing in constants file](https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/21342c37561ce317083b685c9e04ec349b6d8593).
> 
> Fixed in master branch, please pull the changes and try again.
> 
> Regards.

Still not working on my side. Version number is 
`Current Bot version:
1.19.3 (27/05/2021)`
by 
`docker run -d --name captcha-bot --env CAPTCHABOT_TOKEN="xxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxx" --env CAPTCHABOT_OWNER="xxxxxxxx" --env CAPTCHABOT_INIT_LANG="DE" --restart always captcha-bot`

**Comment by J-Rios** [comment]
Sorry, didn't have time to test it, maybe next weekend I take a look into it.

**Comment by J-Rios** [comment]
Tested and it seems working ok...

I'm not familiar with Docker usage, but maybe your issue could be related to your Docker instance is cached in your system? 

Please try to make a new deploy by `make force` (note that Dockerfile download and deploy the project code from Github and not from what you have cloned and have locally):

1. Stop and remove any previous Bot Docker container:

```bash
sudo docker ps
sudo docker stop captcha-bot
sudo docker rm captcha-bot
```
2. Renew and create a new fresh Docker container using "force" make target to ignore any previous cached data:

```bash
cd docker
sudo make force
```

3. Launch again the Docker container:

```bash
sudo docker run -d --name captcha-bot --env CAPTCHABOT_TOKEN="xxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxx" --env CAPTCHABOT_OWNER="xxxxxxxx" --env CAPTCHABOT_INIT_LANG="DE" --restart always captcha-bot
```

**Comment by SA7BNT** [comment]
Thanks for your help, seems to work now.
